config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  root 'homes#index'
  get "home/about" => "homes#about"
  devise_for :users

# フォロー機能
	resources :users do
		resource :relationships, only: [:create, :destroy]
		get :follows, on: :member
		get :followers, on: :member
	end

	resources :books do
		# いいね機能
	  resource :favorites, only: [:create, :destroy]
	  # コメント機能 resources 複数コメントをid判別している
	  resources :book_comments, only: [:create, :destroy]
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

belongs_to :user

# コメント機能
has_many :book_comments, dependent: :destroy
# いいね機能
has_many :favorites, dependent: :destroy
 	def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
  end

validates :body, presence: true, length: { maximum: 200 }
validates :title, presence: true
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
# コメント機能
belongs_to :user
belongs_to :book

# presence: true 空欄だとfalse
validates :comment, presence: true, length: { maximum: 50 }

end

app/models/favorite.rb
class Favorite < ApplicationRecord
# いいね機能
belongs_to :book
belongs_to :user

end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

# コメント機能
	has_many :books, dependent: :destroy
	attachment :profile_image
	has_many :book_comments, dependent: :destroy

# いいね機能
	has_many :favorites, dependent: :destroy

	# フォロー
	# 自分がフォロしているユーザーとの関連
	has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
	has_many :followings, through: :active_relationships, source: :follower
	# 自分がフォローされるユーザーとの関連
	has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
	has_many :followers, through: :passive_relationships, source: :following

	validates :name, presence: true, length: { in: 2..20 }
	validates :introduction, length: { maximum: 50 }
	# validate :add_error_sample

	def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
  user_path(current_user.id)
	end

	protected
	def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email]) # 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
  	# devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	# コメント
def create
	book = Book.find(params[:book_id])
	comment = BookComment.new(book_comment_params)
	comment.user_id = current_user.id
	comment.book_id = book.id
	comment.save
	redirect_to book_path(book)
end

def destroy
	@book = Book.find(params[:book_id])
	comment = current_user.book_comments.find(params[:id])
	comment.destroy
	redirect_to books_path
end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
  	@book = Book.new
  	@books = Book.all
    @user = current_user
  end

  def show
    @bookn = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    # コメント機能
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if current_user.id == @book.user_id
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      render action: :edit
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       flash[:notice] = "successfully"
       redirect_to book_path(@book.id)
    else
       @books = Book.all
       redirect_to books_path
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  private
    def book_params
        params.require(:book).permit(:title, :body)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: book.id)
		favorite.save
		# いいね機能、押されたところのviewに戻る　request.referrer
		redirect_to request.referrer
	end

	def destroy
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: book.id)
		favorite.destroy
		redirect_to request.referrer
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
  	follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to request.referrer
  end

  def destroy
  	follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to request.referrer
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
  	@user = User.find(params[:id])
    @book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
    if current_user.id == @user.id
    else
       redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "successfully"
       redirect_to user_path(@user.id)
    else
      flash[:notice] = "erorr"
       render action: :edit
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<%= notice %>

<div class="container">

  <div class="row">
	  <div class="col-md-6 col-md-offset-3">
  		<h1>Editing Book</h1>

      <%= form_for(@book) do |f| %>
      <% if@book.errors.any? %>
              <%= @book.errors.count %>件のerrorが発生しました
                <% @book.errors.full_messages.each do |message| %>
                  <%= message %>
              <% end %>
            <% end %>

      <div class="field row">
        <h4>Title</h4>
         <div><%= f.text_field :title, class: "col-xs-12 book_title" %></div>
      </div>

      <div class="field row">
        <h4>Opinion</h4>
        <div>
          <%= f.text_area :body, class: "col-xs-12 book_body" %>
        </div>
      </div>

      <div class="actions row">
          <div>
            <%= f.submit "Update book", class: "btn btn-primary col-xs-12" %>
            </div>
        <% end %>

          <div>
            <%= link_to "Show", book_path(@book.id) %>
            <%= link_to "Back", books_path %>
          </div>
      </div>
      <div class="col-md-3"></div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= notice %>

<div class="container">
        <!-- <p id="notice"></p> -->
  <div class="row">
  	<div class="col-xs-3">
    	<h2>User info</h2>
    		<%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
    		<table class="table">
	      	<tbody>
		      	<tr>
		    	  	<th>name</th>
		    	  	<th><%= current_user.name %></th>
		      	</tr>
		      	<tr>
		    	  	<th>introduction</th>
		    	  	<th><%= current_user.introduction %></th>
		      	</tr>
            <tr>
              <th>follows</th>
              <th>
                <%= link_to follows_user_path(@user) do %>
                <%= @user.active_relationships.count %>
                <% end %>
              </th>
            </tr>
            <tr>
              <th>following</th>
              <th>
                <%= link_to followers_user_path(@user) do %>
                <%= @user.passive_relationships.count %>
                <% end %>
              </th>
            </tr>
					</tbody>
				</table>
					<%= link_to "", edit_user_path(current_user), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench edit' %>

			    <h2>New book</h2>
			  	<%= form_for(@book) do |f| %>
			  		<% if@book.errors.any? %>
        			<%= @book.errors.count %>件のerrorが発生しました
        				<% @book.errors.full_messages.each do |message| %>
            			<%= message %>
        			<% end %>
    				<% end %>

    				<h4>Title</h4>
    				<%= f.text_field :title %>

    				<h4>Opinion</h4>
    				<%= f.text_area :body %>
						<%= f.submit "Create book", class: 'btn btn-primary col-xs-12' %>
    			<% end %>
			</div>
			<div class="col-xs-9">
    		<h2>Books</h2>
    			<table class="table table-hover table-inverse">
  					<thead>
    					<tr>
      					<th></th>
      					<th>Title</th>
      					<th>Opinion</th>
      					<th colspan="3"></th>
    					</tr>
  					</thead>
  					<tbody>
    					<% @books.each do |book| %>
    						<tr>
    							<td>
    								<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
                  </td>
    							<td>
    								<%= link_to book_path(book.id) do %>
    								<%= book.title %>
                    <% end %>
    							</td>
    							<td>
                    <%= book.body %>
                  </td>
                  <!-- 下記　いいね機能。eachの変数|book|を用いる-->
                  <% if book.favorited_by?(current_user) %>
                    <td>
                      <%= link_to book_favorites_path(book), method: :delete do %>
                      <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                      <%= book.favorites.count %> いいね
                      <% end %>
                    </td>
                    <% else %>
                    <td>
                      <%= link_to book_favorites_path(book), method: :post do %>
                      <i class="fa fa-heart" aria-hidden="true"></i>
                      <%= book.favorites.count %> いいね
                      <% end %>
                    </td>
                    <!-- 下記、コメント -->
                    <td>
                      <%= book.book_comments.count %>件コメント
                    </td>
    							<% end %>
    						</tr>
              <% end %>
  					</tbody>
					</table>
  		</div>
	</div>
</div>

app/views/books/show.html.erb
<%= notice %>

<div class="container">
        <!-- <p id="notice"></p> -->
  <div class="row">
  	<div class="col-xs-3">
    	<h2>User info</h2>
    		<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
    		<table class="table">
	      	<tbody>
		      	<tr>
		    	  	<th>name</th>
		    	  	<th><%= @user.name %></th>
		      	</tr>
		      	<tr>
		    	  	<th>introduction</th>
		    	  	<th><%= @user.introduction %></th>
		      	</tr>
					</tbody>
				</table>
          <% if @book.user == current_user %>
					<%= link_to "", edit_user_path(@user), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench edit' %>
          <% else %>
          <%= link_to "", user_path(current_user), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench edit' %>
          <% end %>
			    <h2>New book</h2>
			  	<%= form_for(@bookn) do |f| %>

    				<h4>Title</h4>
    				<%= f.text_field :title %>

    				<h4>Opinion</h4>
    				<%= f.text_area :body %>
						<%= f.submit "Create book", class: 'btn btn-primary col-xs-12' %>
    			<% end %>
			</div>
			<div class="col-xs-9">
    		<h2>Book detail</h2>
    		<table class="table table-hover table-inverse">
  					<thead>
    					<tr>
      					<th></th>
      					<th></th>
      					<th></th>
      					<th colspan="3"></th>
    					</tr>
  					</thead>
  				  <tbody>
  					  <tr>
  							<td>
  								<%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
                  <%= link_to user_path(@user) do %>
  								<%= @user.name %>
                  <% end %>
                </td>
  							<td>
  								<%= link_to book_path(@book.id) do %>
  								<%= @book.title %>
  								<% end %>
  							</td>
  							<td>
                  <%= @book.body %>
                </td>
                <!-- 下記、いいね機能 -->
                <% if @book.favorited_by?(current_user) %>
                  <td>
                    <%= link_to book_favorites_path(@book), method: :delete do %>
                    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                    <%= @book.favorites.count %> いいね
                    <% end %>
                  </td>
                <% else %>
                  <td>
                    <%= link_to book_favorites_path(@book), method: :post do %>
                      <i class="fa fa-heart" aria-hidden="true"></i>
                      <%= @book.favorites.count %> いいね
                      <% end %>
                  </td>
                <% end %>
                <!-- 下記、コメント件数 -->
                <td>
                  <%= @book.book_comments.count %>件コメント
                </td>
                <% if @book.user == current_user %>
    							<td>
                    <%= link_to "edit", edit_book_path %>
                  </td>
    							<td>
                    <%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "Are you sure？"} %>
                  </td>
  							<% end %>
  					  </tr>
  				  </tbody>
				</table>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>日時</th>
              <th>名前</th>
              <th>コメント</th>
            </tr>
          </thead>
          <% @book.book_comments.each do |book_comment| %>
          <tbody>
            <td>
              <%= book_comment.created_at.strftime("%Y年%m月%d日 %H時%M分") %>
            </td>
            <td>
              <%= book_comment.user.name %>
            </td>
            <td>
              <%= book_comment.comment %>
            </td>
          <% if book_comment.user_id == current_user.id %>
            <td>
              <!-- 削除 -->
               <%= link_to "Destroy", book_book_comment_path(book_comment.book_id, book_comment.id), method: :delete %>
            </td>
          <% end %>
          </tbody>
          <% end %>
        </table>
        <!-- 下記　コメント機能 -->
        <table>
              <%= form_for [@book, @book_comment] do |f| %>
              <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
              <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
              <% end %>
        </table>
  		</div>
	</div>
</div>

app/views/homes/about.html.erb
<h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>

app/views/homes/index.html.erb
      <%= notice %>
      <div class="container">
      	<div class="row">
  				<div class="top-message col-md-offset-3 col-md-6">
    				<h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
          	<p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
          	<p>you can share and exchange  your opinions , inpressions , and emotions</p>
          	<p> about varioius books!</p>

    				<div class="btn-wrapper">
      				<div class="row">
         				<p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
      				</div>
     				 	<div class="row">
        				<p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
      				</div>
    				</div>
  				</div>
				</div>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- 下記いいね機能ハート表示　fontawesome(ホームページから取得) -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
  </head>

  <body>

    <header  class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>

        <% if user_signed_in? %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to " Home ", user_path(current_user.id), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to " Users ", users_path, class: 'glyphicon glyphicon-user user' %></li>
            <li><%= link_to " Books ", books_path, class: 'glyphicon glyphicon-book Books' %></li>
            <li><%= link_to " logout ", destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to " Home ", root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to " About ", home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to " sign up ", new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to " login ", new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
          </ul>
        <% end %>
        </nav>
      </div>
    </header>

    <div class="body">
    <%= yield %>
    </div>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/users/edit.html.erb
<%= notice %>

<div class="container">
<h2>User info</h2>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <%= @user.errors.count %>件のerrorが発生しました
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>
    <div>
      <div class="form-group has-icon">
        <strong>Name</strong><%= f.text_field :name %>
    </div>
    <div>
      <div class="form-group has-icon">
        <strong>Image</strong><%= f.attachment_field :profile_image %>
    </div>
     <div>
      <div class="form-group has-icon">
        <strong>Introduction</strong><%= f.text_field :introduction %>
    </div>
    <%= f.submit "Update User" %>
<% end%>

app/views/users/followers.html.erb
<div class="container">
	<div class="row">
		<h1>followwrs</h1>

			<table class="table table-hover table-inverse">
						<tr>
							<th>image</th>
							<th>name</th>
						</tr>
					<tbody>
						<% @users.each do |user| %>
							<tr>
							<td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %></td>
  						<td><%= user.name %></td>
  						<td>フォロー数<%= user.active_relationships.count %></td>
  						<td>フォロワー数<%= user.passive_relationships.count %></td>
								<% if current_user != user %>
        					<% if user.followed_by?(current_user) %>
										<td><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></td>
              		<% else %>
              			<td><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
              		<% end %>
            		<% end %>
            	<td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
            <% end %>
					</tbody>
			</table>
	</div>
</div>

app/views/users/follows.html.erb
<div class="container">
	<div class="row">
		<h1>follows</h1>

			<table class="table table-hover table-inverse">
						<tr>
							<th>image</th>
							<th>name</th>
						</tr>
					<tbody>
						<% @users.each do |user| %>
							<tr>
							<td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %></td>
  						<td><%= user.name %></td>
  						<td>フォロー数<%= user.active_relationships.count %></td>
  						<td>フォロワー数<%= user.passive_relationships.count %></td>
								<% if current_user != user %>
        					<% if user.followed_by?(current_user) %>
										<td><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></td>
              		<% else %>
              			<td><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
              		<% end %>
            		<% end %>
            	<td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
            <% end %>
					</tbody>
			</table>
	</div>
</div>

app/views/users/index.html.erb
<%= notice %>

<div class="container">
        <!-- <p id="notice"></p> -->
  <div class="row">
  	<div class="col-xs-3">
    	<h2>User info</h2>
    		<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
    		<table class="table">
	      	<tbody>
		      	<tr>
		    	  	<th>name</th>
		    	  	<th><%= current_user.name %></th>
		      	</tr>
		      	<tr>
		    	  	<th>introduction</th>
		    	  	<th><%= current_user.introduction %></th>
		      	</tr>
            <tr>
              <th>follows</th>
              <th>
                <%= link_to follows_user_path(@user) do %>
                <%= @user.active_relationships.count %>
                <% end %>
              </th>
            </tr>
            <tr>
              <th>following</th>
              <th>
                <%= link_to followers_user_path(@user) do %>
                <%= @user.passive_relationships.count %>
                <% end %>
              </th>
            </tr>
					</tbody>
				</table>
				<!-- <div class="row"> -->
					<%= link_to "", edit_user_path(current_user), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench edit' %>
				<!-- </div> -->

			    <h2>New book</h2>
			  <!-- <div class="field row"> -->
			  	<%= form_for(@book) do |f| %>

    				<h4>タイトル</h4>
    				<%= f.text_field :title %>

    				<h4>本文</h4>
    				<%= f.text_area :body %>
						<%= f.submit "Create book", class: 'btn btn-primary col-xs-12' %>
    			<% end %>
			</div>
			<div class="col-xs-9">
    		<h2>Users</h2>
    		<table class="table table-hover table-inverse">
  					<thead>
    					<tr>
      					<th>image</th>
      					<th>name</th>
      					<th colspan="3"></th>
    					</tr>
  					</thead>
  					<tbody>
  						<% @users.each do |user| %>
  						<tr>
  							<td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %></td>
  							<td><%= user.name %></td>
            <% if current_user != user %>
              <% if user.followed_by?(current_user) %>
              <td>
                <%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %>
              </td>
              <% else %>
              <td>
                <%=link_to "フォローする", user_relationships_path(user.id), method: :post %>
              </td>
              <% end %>
            <% end %>
              <td><%= link_to "Show", user_path(user.id) %></td>
  						</tr>
  						<% end %>
  					</tbody>
					</table>
  		</div>
	</div>
</div>

app/views/users/show.html.erb
<%= notice %>

<div class="container">
        <!-- <p id="notice"></p> -->
  <div class="row">
  	<div class="col-xs-3">
    	<h2>User info</h2>
    		<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
    		<table class="table">
	      	<tbody>
		      	<tr>
		    	  	<th>name</th>
		    	  	<th><%= @user.name %></th>
		      	</tr>
		      	<tr>
		    	  	<th>introduction</th>
		    	  	<th><%= @user.introduction %></th>
		      	</tr>
            <tr>
              <th>follows</th>
              <th>
                <%= link_to follows_user_path(@user) do %>
                <%= @user.active_relationships.count %>
                <% end %>
              </th>
            </tr>
            <tr>
              <th>following</th>
              <th>
                <%= link_to followers_user_path(@user) do %>
                <%= @user.passive_relationships.count %>
                <% end %>
              </th>
            </tr>
					</tbody>

				</table>
        <% if current_user != @user %>
              <% if @user.followed_by?(current_user) %>
                <%=link_to "フォロー済み", user_relationships_path(@user.id), method: :delete %>
              <% else %>
                <%=link_to "フォローする", user_relationships_path(@user.id), method: :post %>
              <% end %>
        <% end %>
					<%= link_to "", edit_user_path(@user), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench edit' %>

			    <h2>New book</h2>
			  	<%= form_for(@book) do |f| %>

    				<h4>Title</h4>
    				<%= f.text_field :title %>

    				<h4>Opinion</h4>
    				<%= f.text_area :body %>
						<%= f.submit "Create book", class: 'btn btn-primary col-xs-12' %>
    			<% end %>
			</div>
			<div class="col-xs-9">
    		<h2>Books</h2>
    			<table class="table table-hover table-inverse">
  					<thead>
    					<tr>
      					<th></th>
      					<th>Title</th>
      					<th>Opinion</th>
      					<th colspan="3"></th>
    					</tr>
  					</thead>
  					<% @user.books.each do |book| %>
  					<tbody>
  						<tr>
  							<td>
  								<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
  							</td>
  							<td>
  								<%= link_to book_path(book.id) do %>
  								<%= book.title %>
  								<% end %>
  							</td>
  							<td>
                  <%= book.body %>
                </td>
                <td>
                  <%= book.book_comments.count %>件コメント
                </td>
  						</tr>
  					</tbody>
  					<% end %>
					</table>
  		</div>
	</div>
</div>